import { 
  HeavyCraneAsset, 
  WeldingBayAsset, 
  CncCutterAsset, 
  FleetSummary, 
  MaintenanceTask, 
  WorkOrder, 
  SafeZoneCalibration,
  NavalWpsAuditRecord 
} from '../types/dashboard';

export const INITIAL_CRANES: HeavyCraneAsset[] = [
  {
    id: 'crane-1',
    name: 'Goliath Gantry 600T',
    code: 'CR-G600-01',
    category: 'crane',
    model: 'Konecranes Goliath (Retrofitted 2024)',
    location: 'Dry Dock 01 - Main Hull Assembly',
    gps: {
      latitude: 37.788251,
      longitude: -122.387214,
      formatted: '37.788251° N, 122.387214° W',
      altitudeMeters: 48.0,
      hdopPrecision: 0.65,
      headingDegrees: 84,
      satellites: 16,
    },
    gridX: 42,
    gridY: 28,
    status: 'operating',
    safeWorkingLimitTons: 600,
    currentLoadTons: 418.5,
    loadPercentage: 69.8,
    proximityDistanceMeters: 14.8,
    nearestObstacle: 'Dry Dock Wall (North Sector)',
    proximityStatus: 'safe',
    gearboxVibrationScore: 2.1,
    gearboxHealthRating: 'optimal',
    structuralStrainMicrostrain: 540,
    strainHistory: [
      { time: '08:00', strain: 380, load: 320 },
      { time: '09:00', strain: 490, load: 410 },
      { time: '10:00', strain: 580, load: 460 },
      { time: '11:00', strain: 520, load: 430 },
      { time: '12:00', strain: 310, load: 180 },
      { time: '13:00', strain: 540, load: 418.5 },
    ],
    vibrationFrequencies: [
      { freq: '10 Hz (Shaft 1X)', amplitude: 0.42, baseline: 0.45 },
      { freq: '30 Hz (Mesh 3X)', amplitude: 1.15, baseline: 1.20 },
      { freq: '120 Hz (Gear Tooth)', amplitude: 0.85, baseline: 0.80 },
      { freq: '350 Hz (Bearing BPFO)', amplitude: 0.32, baseline: 0.35 },
      { freq: '800 Hz (Harmonics)', amplitude: 0.18, baseline: 0.20 },
    ],
    powerDrawKw: 142.5,
    todayLiftsCount: 14,
    boltOnSensors: {
      lidar: true,
      uwbTag: true,
      strainGauges: true,
      vibrationNode: true,
    },
  },
  {
    id: 'crane-2',
    name: 'Overhead Gantry 150T',
    code: 'CR-OH150-02',
    category: 'crane',
    model: 'Demag Industrial Overhead (Retrofitted)',
    location: 'Hull Block Fabrication Bay B',
    gps: {
      latitude: 37.787640,
      longitude: -122.385830,
      formatted: '37.787640° N, 122.385830° W',
      altitudeMeters: 22.4,
      hdopPrecision: 0.72,
      headingDegrees: 195,
      satellites: 15,
    },
    gridX: 68,
    gridY: 54,
    status: 'warning',
    safeWorkingLimitTons: 150,
    currentLoadTons: 134.2,
    loadPercentage: 89.5,
    proximityDistanceMeters: 2.8,
    nearestObstacle: 'Pillar B-14 & Hull Block Module #4',
    proximityStatus: 'caution',
    gearboxVibrationScore: 6.4,
    gearboxHealthRating: 'elevated',
    structuralStrainMicrostrain: 920,
    strainHistory: [
      { time: '08:00', strain: 420, load: 80 },
      { time: '09:00', strain: 640, load: 110 },
      { time: '10:00', strain: 810, load: 125 },
      { time: '11:00', strain: 780, load: 120 },
      { time: '12:00', strain: 400, load: 50 },
      { time: '13:00', strain: 920, load: 134.2 },
    ],
    vibrationFrequencies: [
      { freq: '10 Hz (Shaft 1X)', amplitude: 0.88, baseline: 0.50 },
      { freq: '30 Hz (Mesh 3X)', amplitude: 2.85, baseline: 1.40 },
      { freq: '120 Hz (Gear Tooth)', amplitude: 3.20, baseline: 1.10 },
      { freq: '350 Hz (Bearing BPFO)', amplitude: 1.95, baseline: 0.60 },
      { freq: '800 Hz (Harmonics)', amplitude: 0.72, baseline: 0.30 },
    ],
    powerDrawKw: 88.0,
    todayLiftsCount: 22,
    boltOnSensors: {
      lidar: true,
      uwbTag: true,
      strainGauges: true,
      vibrationNode: true,
    },
  },
  {
    id: 'crane-3',
    name: 'Portal Jib Crane 80T',
    code: 'CR-JB80-03',
    category: 'crane',
    model: 'Gottwald Rail Portal (Retrofitted)',
    location: 'Pier 03 - Vessel Outfitting Quay',
    gps: {
      latitude: 37.789120,
      longitude: -122.388450,
      formatted: '37.789120° N, 122.388450° W',
      altitudeMeters: 34.2,
      hdopPrecision: 0.68,
      headingDegrees: 310,
      satellites: 17,
    },
    gridX: 24,
    gridY: 72,
    status: 'operating',
    safeWorkingLimitTons: 80,
    currentLoadTons: 38.6,
    loadPercentage: 48.2,
    proximityDistanceMeters: 19.5,
    nearestObstacle: 'Mooring Bollard #7',
    proximityStatus: 'safe',
    gearboxVibrationScore: 1.8,
    gearboxHealthRating: 'optimal',
    structuralStrainMicrostrain: 360,
    strainHistory: [
      { time: '08:00', strain: 290, load: 30 },
      { time: '09:00', strain: 340, load: 35 },
      { time: '10:00', strain: 410, load: 45 },
      { time: '11:00', strain: 380, load: 40 },
      { time: '12:00', strain: 220, load: 15 },
      { time: '13:00', strain: 360, load: 38.6 },
    ],
    vibrationFrequencies: [
      { freq: '10 Hz (Shaft 1X)', amplitude: 0.35, baseline: 0.40 },
      { freq: '30 Hz (Mesh 3X)', amplitude: 0.95, baseline: 1.00 },
      { freq: '120 Hz (Gear Tooth)', amplitude: 0.65, baseline: 0.70 },
      { freq: '350 Hz (Bearing BPFO)', amplitude: 0.28, baseline: 0.30 },
      { freq: '800 Hz (Harmonics)', amplitude: 0.15, baseline: 0.18 },
    ],
    powerDrawKw: 62.4,
    todayLiftsCount: 18,
    boltOnSensors: {
      lidar: true,
      uwbTag: true,
      strainGauges: true,
      vibrationNode: true,
    },
  },
];

export const INITIAL_WELDING_BAYS: WeldingBayAsset[] = [
  {
    id: 'weld-1',
    name: 'Welding Bay 01 - Bulkhead Sub-Assembly',
    code: 'WB-01-BK',
    category: 'welding',
    operator: 'Marcus Vance (Cert AWS D1.1)',
    location: 'Fabrication Hall East - Bay A1',
    gps: {
      latitude: 37.788480,
      longitude: -122.385420,
      formatted: '37.788480° N, 122.385420° W',
      altitudeMeters: 12.0,
      hdopPrecision: 0.80,
      satellites: 14,
    },
    gridX: 74,
    gridY: 22,
    status: 'operating',
    wpsSpec: 'WPS-ASME-IX-FCAW-45',
    liveVoltage: 28.4,
    liveCurrent: 245,
    targetVoltageMin: 26.0,
    targetVoltageMax: 30.0,
    targetCurrentMin: 220,
    targetCurrentMax: 260,
    wpsCompliancePercentage: 97.4,
    arcOnTimePercentage: 71.8,
    defectProbabilityScore: 2.3,
    shieldingGasFlowLpm: 18.2,
    wireFeedSpeedMpm: 8.5,
    wireConsumedKgToday: 34.2,
    gasConsumedCubicMetersToday: 14.8,
    bayAqiPm25: 18,
    bayVocPpm: 0.45,
    fumeHoodRpm: 2400,
    fumeHoodAutoBoost: true,
    waveformStability: 96,
    recentDefectsFlagged: [],
    powerDrawKw: 14.2,
    boltOnSensors: {
      currentTransformers: true,
      visionCamera: true,
      aqiSensors: true,
      smartHood: true,
    },
  },
  {
    id: 'weld-2',
    name: 'Welding Bay 02 - Curved Hull Plating',
    code: 'WB-02-HP',
    category: 'welding',
    operator: 'Elena Rostova (Cert DNV-GL Master)',
    location: 'Heavy Hull Shop - Bay C2',
    gps: {
      latitude: 37.787320,
      longitude: -122.386750,
      formatted: '37.787320° N, 122.386750° W',
      altitudeMeters: 12.0,
      hdopPrecision: 0.82,
      satellites: 14,
    },
    gridX: 52,
    gridY: 62,
    status: 'warning',
    wpsSpec: 'WPS-DNV-SAW-HULL-12',
    liveVoltage: 33.2,
    liveCurrent: 298,
    targetVoltageMin: 27.0,
    targetVoltageMax: 31.0,
    targetCurrentMin: 240,
    targetCurrentMax: 280,
    wpsCompliancePercentage: 81.2,
    arcOnTimePercentage: 64.5,
    defectProbabilityScore: 14.8,
    shieldingGasFlowLpm: 14.1,
    wireFeedSpeedMpm: 9.8,
    wireConsumedKgToday: 48.0,
    gasConsumedCubicMetersToday: 19.5,
    bayAqiPm25: 38,
    bayVocPpm: 0.92,
    fumeHoodRpm: 2850,
    fumeHoodAutoBoost: true,
    waveformStability: 79,
    recentDefectsFlagged: [
      { id: 'def-101', time: '13:12', type: 'Voltage Spike (33.2V) -> Risk of Porosity', severity: 'med' },
      { id: 'def-102', time: '12:44', type: 'Gas Flow Dip (12.4 L/min) -> Sub-surface slag inclusion risk', severity: 'high' },
    ],
    powerDrawKw: 18.5,
    navalSteelGrade: 'DMR 249A',
    heatInputKjPerMm: 1.78,
    heatInputStatus: 'high_ndt_required',
    interpassTempCelsius: 192,
    ndtRequisitionFlagged: true,
    confinedSpaceAtmosphere: {
      locationName: 'Double Bottom Cell 4B (Fr 42-46) - Ballast Tank',
      oxygenPct: 20.8,
      oxygenStatus: 'safe',
      argonDisplacementPpm: 320,
      hydrocarbonLelPct: 0.0,
      blowerCfm: 2400,
      blowerInterlockEngaged: true,
      certifiedWorkersInside: 2,
    },
    boltOnSensors: {
      currentTransformers: true,
      visionCamera: true,
      aqiSensors: true,
      smartHood: true,
    },
  },
  {
    id: 'weld-3',
    name: 'Welding Bay 03 - Deck Stiffener Line',
    code: 'WB-03-DS',
    category: 'welding',
    operator: 'Liam Chen (Cert Lloyd\'s Register)',
    location: 'Panel Line Hall - Bay D1',
    gps: {
      latitude: 37.786950,
      longitude: -122.384910,
      formatted: '37.786950° N, 122.384910° W',
      altitudeMeters: 12.0,
      hdopPrecision: 0.78,
      satellites: 15,
    },
    gridX: 84,
    gridY: 76,
    status: 'operating',
    wpsSpec: 'WPS-LR-MIG-STIFF-08',
    liveVoltage: 27.8,
    liveCurrent: 232,
    targetVoltageMin: 26.0,
    targetVoltageMax: 29.5,
    targetCurrentMin: 215,
    targetCurrentMax: 250,
    wpsCompliancePercentage: 98.6,
    arcOnTimePercentage: 76.2,
    defectProbabilityScore: 1.1,
    shieldingGasFlowLpm: 19.0,
    wireFeedSpeedMpm: 7.8,
    wireConsumedKgToday: 29.4,
    gasConsumedCubicMetersToday: 12.1,
    bayAqiPm25: 14,
    bayVocPpm: 0.32,
    fumeHoodRpm: 2100,
    fumeHoodAutoBoost: true,
    waveformStability: 98,
    recentDefectsFlagged: [],
    powerDrawKw: 12.8,
    boltOnSensors: {
      currentTransformers: true,
      visionCamera: true,
      aqiSensors: true,
      smartHood: true,
    },
  },
  {
    id: 'weld-4',
    name: 'Welding Bay 04 - Pipe Spooling Bay',
    code: 'WB-04-PS',
    category: 'welding',
    operator: 'Tariq Al-Mansoor (Cert ASME B31.3)',
    location: 'Pipe & Machinery Outfitting Shop',
    gps: {
      latitude: 37.788850,
      longitude: -122.387900,
      formatted: '37.788850° N, 122.387900° W',
      altitudeMeters: 12.0,
      hdopPrecision: 0.85,
      satellites: 13,
    },
    gridX: 32,
    gridY: 82,
    status: 'operating',
    wpsSpec: 'WPS-ASME-TIG-PIPE-02',
    liveVoltage: 16.5,
    liveCurrent: 140,
    targetVoltageMin: 14.5,
    targetVoltageMax: 18.0,
    targetCurrentMin: 120,
    targetCurrentMax: 155,
    wpsCompliancePercentage: 96.0,
    arcOnTimePercentage: 58.9,
    defectProbabilityScore: 3.4,
    shieldingGasFlowLpm: 12.5,
    wireFeedSpeedMpm: 3.2,
    wireConsumedKgToday: 11.2,
    gasConsumedCubicMetersToday: 9.8,
    bayAqiPm25: 11,
    bayVocPpm: 0.28,
    fumeHoodRpm: 1800,
    fumeHoodAutoBoost: true,
    waveformStability: 94,
    recentDefectsFlagged: [],
    powerDrawKw: 7.2,
    boltOnSensors: {
      currentTransformers: true,
      visionCamera: true,
      aqiSensors: true,
      smartHood: true,
    },
  },
];

export const INITIAL_CNC_CUTTERS: CncCutterAsset[] = [
  {
    id: 'cnc-1',
    name: 'Legacy CNC Plasma Cutter #01',
    code: 'CNC-PL-01',
    category: 'cnc',
    brandAndAge: 'ESAB Telerex (1996 - Retrofitted with Edge I/O & OCR)',
    location: 'Plate Processing Hall - Bay 1',
    gps: {
      latitude: 37.789210,
      longitude: -122.388900,
      formatted: '37.789210° N, 122.388900° W',
      altitudeMeters: 14.5,
      hdopPrecision: 0.75,
      satellites: 15,
    },
    gridX: 18,
    gridY: 36,
    machineState: 'cutting',
    status: 'operating',
    oeeScore: 78.4,
    oeeAvailability: 88.5,
    oeePerformance: 91.2,
    oeeQuality: 97.1,
    cuttingSpeedMpm: 2.85,
    gasPressureBar: 6.2,
    gasFlowScmh: 4.8,
    isLeakingGas: false,
    leakRateEstimate: 0.0,
    nozzleWearPercentage: 74,
    nozzleEstimatedHoursRemaining: 8.5,
    ocrTerminalFeed: [
      { timestamp: '13:34:12', text: 'EDGE_IO: 24V PIN_GREEN_HIGH -> STATE: RUNNING', level: 'info' },
      { timestamp: '13:34:15', text: 'OCR_READ: "N-408 G01 X2450.0 Y1200.0 F2850"', level: 'cut' },
      { timestamp: '13:34:18', text: 'GAS_METER: O2=4.8 Sm3/h | CUT_CYCLE_MATCH=OK', level: 'info' },
      { timestamp: '13:34:22', text: 'TORCH_HEIGHT_SENSOR: ARC VOLTAGE CONTROL 148V', level: 'info' },
    ],
    activeProgram: 'HULL_SECTION_B4_FRAME_72.NC',
    plateMaterial: 'AH36 High-Tensile Marine Steel',
    plateThicknessMm: 24,
    powerDrawKw: 48.6,
    boltOnSensors: {
      edgeIoModule: true,
      gasFlowMeter: true,
      ocrCrtCamera: true,
      edgeGateway: true,
    },
  },
  {
    id: 'cnc-2',
    name: 'Retrofitted Gantry Flame Cutter #02',
    code: 'CNC-FL-02',
    category: 'cnc',
    brandAndAge: 'Messer Omnimat (2001 - Retrofitted with Inline Flow Meters)',
    location: 'Heavy Plate Cutting Yard - Bay 2',
    gps: {
      latitude: 37.788640,
      longitude: -122.387550,
      formatted: '37.788640° N, 122.387550° W',
      altitudeMeters: 14.5,
      hdopPrecision: 0.79,
      satellites: 14,
    },
    gridX: 38,
    gridY: 48,
    machineState: 'idle',
    status: 'warning',
    oeeScore: 68.2,
    oeeAvailability: 72.0,
    oeePerformance: 96.0,
    oeeQuality: 98.5,
    cuttingSpeedMpm: 0.0,
    gasPressureBar: 5.8,
    gasFlowScmh: 0.85,
    isLeakingGas: true,
    leakRateEstimate: 14.2, // L/min leaking during idle!
    nozzleWearPercentage: 42,
    nozzleEstimatedHoursRemaining: 24.0,
    ocrTerminalFeed: [
      { timestamp: '13:28:01', text: 'EDGE_IO: 24V PIN_AMBER_HIGH -> STATE: IDLE', level: 'warn' },
      { timestamp: '13:28:05', text: 'AI_AUDIT: GAS FLOW (0.85 Sm3/h) DETECTED DURING IDLE STATE', level: 'error' },
      { timestamp: '13:28:10', text: 'LEAK_FLAG: Suspected Solenoid Valve #2 O-ring Seal Degradation', level: 'error' },
      { timestamp: '13:28:18', text: 'OCR_READ: "PROGRAM PAUSED - M00 AWAITING CRANE UNLOAD"', level: 'info' },
    ],
    activeProgram: 'BOW_THRUSTER_BULKHEAD_01.NC',
    plateMaterial: 'DH36 Structural Marine Steel',
    plateThicknessMm: 40,
    powerDrawKw: 12.4,
    boltOnSensors: {
      edgeIoModule: true,
      gasFlowMeter: true,
      ocrCrtCamera: true,
      edgeGateway: true,
    },
  },
  {
    id: 'cnc-3',
    name: 'Multi-Torch Plasma Cutter #03',
    code: 'CNC-PL-03',
    category: 'cnc',
    brandAndAge: 'Koike Aronson (2006 - Edge Gateway Connected)',
    location: 'Plate Processing Hall - Bay 3',
    gps: {
      latitude: 37.789450,
      longitude: -122.389200,
      formatted: '37.789450° N, 122.389200° W',
      altitudeMeters: 14.5,
      hdopPrecision: 0.74,
      satellites: 16,
    },
    gridX: 14,
    gridY: 58,
    machineState: 'cutting',
    status: 'operating',
    oeeScore: 84.1,
    oeeAvailability: 92.0,
    oeePerformance: 92.5,
    oeeQuality: 98.8,
    cuttingSpeedMpm: 3.4,
    gasPressureBar: 6.4,
    gasFlowScmh: 5.2,
    isLeakingGas: false,
    leakRateEstimate: 0.0,
    nozzleWearPercentage: 88,
    nozzleEstimatedHoursRemaining: 3.2,
    ocrTerminalFeed: [
      { timestamp: '13:33:40', text: 'EDGE_IO: PIN_GREEN_HIGH -> CUT SPEED 3400 mm/min', level: 'cut' },
      { timestamp: '13:33:55', text: 'AI_PREDICT: NOZZLE WEAR REACHED 88% (Est. 3.2h life left)', level: 'warn' },
      { timestamp: '13:34:02', text: 'OCR_READ: "N-890 G02 X3800.0 Y950.0 I0 J-50"', level: 'cut' },
    ],
    activeProgram: 'DECK_HATCH_COAMING_REINF.NC',
    plateMaterial: 'Grade A Mild Ship Plate',
    plateThicknessMm: 16,
    powerDrawKw: 52.0,
    boltOnSensors: {
      edgeIoModule: true,
      gasFlowMeter: true,
      ocrCrtCamera: true,
      edgeGateway: true,
    },
  },
];

export const INITIAL_MAINTENANCE_TASKS: MaintenanceTask[] = [
  {
    id: 'maint-1',
    assetId: 'cnc-3',
    assetName: 'Multi-Torch Plasma Cutter #03',
    assetType: 'cnc',
    title: 'Plasma Cutting Nozzle & Electrode Replacement',
    reason: 'IoT gas pressure drop & 88% wear curve reached. Edge AI predicts bevel taper defect within 3.2 operating hours.',
    aiConfidence: 94.2,
    urgency: 'high',
    predictedFailureDate: 'Today, 17:00 (End of Shift 1)',
    estimatedDowntimeHours: 0.5,
    recommendedAction: 'Replace Hypertherm 260A nozzle shield and copper swirl ring during standard 15-min meal break.',
    requiredParts: ['Nozzle Shield 220842 (x2)', 'Swirl Ring 220994', 'O-Ring Lube Pack'],
  },
  {
    id: 'maint-2',
    assetId: 'cnc-2',
    assetName: 'Retrofitted Gantry Flame Cutter #02',
    assetType: 'cnc',
    title: 'Pre-heat Oxygen Solenoid Valve Leak Rectification',
    reason: 'Inline flow meter logged 14.2 L/min continuous idle gas bleed ($185/day utility loss). OCR verified machine is in M00 idle.',
    aiConfidence: 98.7,
    urgency: 'critical',
    predictedFailureDate: 'Active Leak Detected',
    estimatedDowntimeHours: 0.75,
    recommendedAction: 'Inspect and replace degraded Buna-N seal in Gas Manifold Solenoid Valve #2.',
    requiredParts: ['Solenoid Valve Core 24VDC', 'High-pressure Oxygen Seal Kit', 'Leak-Detect Foam'],
  },
  {
    id: 'maint-3',
    assetId: 'crane-2',
    assetName: 'Overhead Gantry 150T',
    assetType: 'crane',
    title: 'Main Hoist Gearbox Harmonic Vibration Re-greasing',
    reason: 'Wireless accelerometer captured 3.2 mm/s RMS peak at 120 Hz gear mesh harmonic. Early indicator of boundary lubrication breakdown.',
    aiConfidence: 89.0,
    urgency: 'medium',
    predictedFailureDate: 'Tomorrow, Shift 1 (08:30)',
    estimatedDowntimeHours: 1.5,
    recommendedAction: 'Perform high-viscosity synthetic ISO VG 460 gear oil replenishment and check bearing lash.',
    requiredParts: ['Synthetic Gear Oil ISO VG 460 (10L)', 'Magnetic Drain Plug Inspection Kit'],
  },
  {
    id: 'maint-4',
    assetId: 'weld-2',
    assetName: 'Welding Bay 02 - Curved Hull Plating',
    assetType: 'welding',
    title: 'Wire Liner Cleaning & Gas Diffuser Swapping',
    reason: 'Digital WPS detected erratic voltage fluctuations (33.2V) and 14.8% defect risk score. Feeder current spikes indicate liner friction.',
    aiConfidence: 91.5,
    urgency: 'high',
    predictedFailureDate: 'Next shift changeover (15:30)',
    estimatedDowntimeHours: 0.25,
    recommendedAction: 'Blow out torch liner with compressed air and fit fresh brass contact tip (1.2mm).',
    requiredParts: ['Teflon Conduit Liner (4.5m)', 'Contact Tips 1.2mm CuCrZr (x5)', 'Ceramic Gas Shroud'],
  },
];

export const INITIAL_FLEET_SUMMARY: FleetSummary = {
  fleetEnergyKw: 420.5,
  fleetEnergyKwhToday: 3120,
  energyStatus: 'normal',
  energySurgeLimitKw: 550.0,
  activeSafetyIncidents: [
    {
      id: 'inc-1',
      assetName: 'Overhead Gantry 150T',
      assetType: 'crane',
      type: 'Proximity Barrier Warning',
      description: 'Crane 2 LiDAR triggered 2.8m warning envelope near Pillar B-14 while carrying 134T Hull Block.',
      severity: 'warning',
      time: '13:31:04',
    },
    {
      id: 'inc-2',
      assetName: 'Welding Bay 02',
      assetType: 'welding',
      type: 'WPS Arc Deviation & AQI Flag',
      description: 'Voltage surged to 33.2V (target max 31.0V). PM2.5 elevated to 38 µg/m³; auto-fume hood engaged at 2850 RPM.',
      severity: 'warning',
      time: '13:12:45',
    },
  ],
  totalYardOee: 74.2,
  yardOeeTarget: 80.0,
  totalSteelTonnageMovedToday: 842.6,
  totalWeldSeamsCompleted: 146,
  activeWorkforceCount: 48,
  retrofittingSavingsEstimate: 14200000, // $14.2M saved vs purchasing new shipyard machinery
  inrAnnualizedSavingsLakhs: 48.6, // ₹48.6 Lakhs annual gas & energy savings
  inrShieldGasSavedMonth: 1.84, // ₹1.84 Lakhs saved via solenoid shutoff
  inrEnergyDemandPeakSaved: 3.20, // ₹3.20 Lakhs peak tariff penalty avoided
  dmrNavalSteelTraceabilityScore: 99.8, // % DQA-N compliance
  activeDqaNavalAuditsCount: 4,
};

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-101',
    title: 'Emergency LiDAR Anti-Collision Radar Recalibration',
    assetId: 'crane-2',
    assetName: 'Overhead Gantry 150T (CR-OH150-02)',
    assetCategory: 'crane',
    priority: 'emergency',
    status: 'dispatched',
    assignedTechnician: 'D. Vance (Lead Rigging Engineer)',
    trade: 'Rigging/Mechanic',
    createdAt: '13:35',
    estimatedHours: 1.0,
    telemetryTrigger: 'LiDAR proximity collapsed to 2.8m near Pillar B-14 while carrying 134T load.',
  },
  {
    id: 'wo-102',
    title: 'CNC-02 Preheat Oxygen Solenoid & O-Ring Reseal',
    assetId: 'cnc-2',
    assetName: 'Messer Retrofit Gantry 02 (CNC-MSR-02)',
    assetCategory: 'cnc',
    priority: 'high',
    status: 'in_progress',
    assignedTechnician: 'M. Kowalski (Gas Systems Specialist)',
    trade: 'Gas Fitter',
    createdAt: '13:15',
    estimatedHours: 0.5,
    telemetryTrigger: 'Inline flow meter detected 18.5 L/min continuous idle gas bleed.',
  },
  {
    id: 'wo-103',
    title: 'WPS Arc Surge & Wire Liner Inspection',
    assetId: 'weld-2',
    assetName: 'Welding Bay 02 - Curved Hull Plating (WB-02)',
    assetCategory: 'welding',
    priority: 'medium',
    status: 'pending',
    assignedTechnician: 'A. Chen (NDT / Quality Inspector)',
    trade: 'Weld Inspector',
    createdAt: '13:20',
    estimatedHours: 0.75,
    telemetryTrigger: 'Arc voltage surged to 33.2V (target max 31.0V) and AQI reached 38 µg/m³.',
  },
  {
    id: 'wo-104',
    title: 'Plasma Torch Consumable Swap (Nozzle 82% Wear)',
    assetId: 'cnc-1',
    assetName: 'ESAB Telerex Heavy Gantry 01 (CNC-ESAB-01)',
    assetCategory: 'cnc',
    priority: 'low',
    status: 'pending',
    assignedTechnician: 'R. Torres (Automation Tech)',
    trade: 'Automation Edge',
    createdAt: '12:45',
    estimatedHours: 0.3,
    telemetryTrigger: 'AI tip wear algorithm flagged remaining nozzle life below 14 hours.',
  },
];

export const INITIAL_SAFE_ZONE_CALIBRATION: SafeZoneCalibration = {
  craneCautionDistanceMeters: 5.0,
  craneHardStopDistanceMeters: 2.0,
  maxStructuralStrainMicrostrain: 1000,
  wpsVoltageTolerancePercent: 10,
  gasLeakIdleThresholdLpm: 5.0,
};

export const INITIAL_NAVAL_WPS_AUDITS: NavalWpsAuditRecord[] = [
  {
    id: 'n-audit-01',
    jointId: 'J-11181-BULB-04',
    hullSection: 'Hull Strake 04 (Bulbous Bow & Sonar Array)',
    navalSteelGrade: 'DMR 249A',
    welderId: 'W-742 (R. Sharma, DQA-N Qualified)',
    wpsSpec: 'WPS-DQA-N-DMR249A-FCAW-08',
    heatInputKjPerMm: 1.42,
    targetHeatInputRange: '1.20 - 1.65 kJ/mm',
    interpassTempCelsius: 145,
    voltageRecorded: 28.2,
    currentRecorded: 240,
    travelSpeedMmPerMin: 286,
    ndtStatus: 'Cleared (UT Pass)',
    irsCompliance: true,
    dqanCompliance: true,
    timestamp: '13:20:14',
  },
  {
    id: 'n-audit-02',
    jointId: 'J-11181-SKEG-02',
    hullSection: 'Double Bottom Keel Plating (Stb Fr 38)',
    navalSteelGrade: 'DMR 249B',
    welderId: 'W-618 (K. Rao, IRS Hull Grade 1)',
    wpsSpec: 'WPS-IRS-DMR249B-SAW-02',
    heatInputKjPerMm: 1.58,
    targetHeatInputRange: '1.30 - 1.70 kJ/mm',
    interpassTempCelsius: 160,
    voltageRecorded: 31.0,
    currentRecorded: 420,
    travelSpeedMmPerMin: 494,
    ndtStatus: 'Cleared (UT Pass)',
    irsCompliance: true,
    dqanCompliance: true,
    timestamp: '12:45:30',
  },
  {
    id: 'n-audit-03',
    jointId: 'J-11181-SONAR-01',
    hullSection: 'Sonar Dome Penetration Collar',
    navalSteelGrade: 'DMR 249B',
    welderId: 'W-904 (A. Verma, Navy Level II)',
    wpsSpec: 'WPS-DQA-N-DMR249B-PULSE-04',
    heatInputKjPerMm: 1.78,
    targetHeatInputRange: '1.20 - 1.60 kJ/mm',
    interpassTempCelsius: 192,
    voltageRecorded: 33.2,
    currentRecorded: 268,
    travelSpeedMmPerMin: 250,
    ndtStatus: 'NDT Requisition Issued (RT Required)',
    irsCompliance: false,
    dqanCompliance: false,
    timestamp: '13:12:45',
  },
  {
    id: 'n-audit-04',
    jointId: 'J-11181-DK-09',
    hullSection: 'Upper Strength Deck Longitudinal (Port)',
    navalSteelGrade: 'EH36',
    welderId: 'W-512 (P. Naidu, IRS Certified)',
    wpsSpec: 'WPS-IRS-EH36-GMAW-12',
    heatInputKjPerMm: 1.35,
    targetHeatInputRange: '1.10 - 1.55 kJ/mm',
    interpassTempCelsius: 138,
    voltageRecorded: 27.5,
    currentRecorded: 225,
    travelSpeedMmPerMin: 274,
    ndtStatus: 'Cleared (UT Pass)',
    irsCompliance: true,
    dqanCompliance: true,
    timestamp: '11:15:20',
  },
];


